### PR TITLE
Move product prices form to bootstrap

### PR DESCRIPTION
**Pull request by mbajur**
Hi, i've made another set of changes - moved product prices form to bootstrpa 3 panels, nothing amazing. 

image

### CODE REVIEW

**Comment by mbajur** [comment]
Oh damn it, commits from my previous PR have been included in here. I've done a fetch upstream before making any changes - any idea what can i do about it ?

**Comment by mbajur** [comment]
I have decided to completely revamp that page (list of variant prices was really long whil there was a lot of white space on the left side. I personally think that right now it's much better), please have a look at it here (`master` variant is marked in blue):

image

If you don't like that, we can revert to the commits with previous scheme.

**Comment by alepore** [comment]
:+1: like this

**Comment by JDutil** [comment]
Thanks

**Pull request closed without merging**
